config/routes.rb
Rails.application.routes.draw do
  resources :ratings
  resources :authors
  resources :users
  resources :novels

  root 'novels#index'

end

app/models/base.rb
class Base < JsonApiClient::Resource
  self.site = "http://localhost:3000/"
end

app/models/novel.rb
class Novel < Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController
  before_action :set_novel, only: [:show, :edit, :update, :destroy]

  # GET /novels
  # GET /novels.json
  def index
    @novels = Novel.all
  end

  # GET /novels/new
  def new
    @novel = Novel.new
  end

  # POST /novels
  # POST /novels.json
  def create
    @novel = Novel.new(novel_params)
    render :new unless @novel.save rescue redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_novel
      @novel = Novel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def novel_params
      params.permit(:title, :description, :author_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/novels_helper.rb
module NovelsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NovelsClient</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/novels/_form.html.erb
<%= form_tag({controller: "novels", action: "create"}, method: "post") do %>
  <% if @novel.errors %>
    <div id="error_explanation">
      <h2><%= pluralize(@novel.errors.count, "error") %> prohibited this novel from being saved:</h2>

      <ul>
      <% @novel.errors.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= label_tag(:title, "Title:") %>
  <%= text_field_tag(:title) %>
  <%= label_tag(:description, "Description:") %>
  <%= text_field_tag(:description) %>
  <%= label_tag(:author_id, "AuthorID:") %>
  <%= text_field_tag(:author_id) %>

  <div class="actions">
    <%= submit_tag %>
  </div>
<% end %>

app/views/novels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Novels</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @novels.each do |novel| %>
      <tr>
        <td><%= novel.id %></td>
        <td><%= novel.title %></td>
        <td><%= novel.description %></td>
        <td><%= novel.author_id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Novel', new_novel_path %>

app/views/novels/new.html.erb
<h1>New Novel</h1>

<%= render 'form' %>

<%= link_to 'Back', novels_path %>